// Package initconfig writes a sane-defaults spore.toml into a project
// that has none, or appends a missing section into a partial one.
//
// The kernel's per-project config (worker mix, coordinator driver,
// alignment thresholds, matter adapters) lives in spore.toml at the
// repo root. Each consumer used to hand-author this file, which left
// projects without one silently running the kernel default of
// "all Claude". This package supplies a documented template plus a
// merge mode (`--section`) that fixes a partial file in place.
package initconfig

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// Block is one logical section of the rendered template. Headers lists
// the exact `[section]` strings whose presence in an existing file
// means the block is already in effect; if any match, the block is not
// re-appended in --section mode. Content is the literal lines (with
// trailing newline) appended when the block is missing.
type Block struct {
	Name    string
	Headers []string
	Content string
}

// Header is the always-on preamble at the top of a freshly generated
// spore.toml.
const Header = `# spore.toml - per-project configuration for the spore harness.
#
# Generated by ` + "`spore init`" + `. Edit by hand: subsequent ` + "`spore init`" + ` runs
# are no-ops unless --force is passed. Use --section <name> to append a
# missing section without rewriting the rest.
#
# Reference: https://github.com/versality/spore#worker-mix
`

// Blocks returns the ordered template sections. The order here is the
// order they appear in the rendered default file and the order
// --section appends choose when multiple are requested in one call.
func Blocks() []Block {
	return []Block{
		{
			Name:    "fleet.workers",
			Headers: []string{"[fleet.workers]", "[fleet.workers.ratio]"},
			Content: `# [fleet.workers] - which agent each spawned worker runs.
# Pick order: explicit task ` + "`agent:`" + ` > rule by complexity > ratio
# balancer > default. The ratio is the only thing most projects need.
[fleet.workers]
default = "claude"

[fleet.workers.ratio]
claude = 67
codex = 33

# [fleet.workers.rules]
# mechanical = "codex"
# deep = "claude"
`,
		},
		{
			Name:    "coordinator",
			Headers: []string{"[coordinator]"},
			Content: `# [coordinator] - the singleton coordinator session driver.
# Empty fields fall through to env-var overrides and kernel defaults.
# [coordinator]
# driver = "claude"
# model = "sonnet"
# brief = "bootstrap/coordinator/role.md"
# external_session_pattern = ""
`,
		},
		{
			Name:    "align",
			Headers: []string{"[align]"},
			Content: `# [align] - pilot-agent alignment-mode exit thresholds.
# [align]
# required_notes = 10
# required_promoted = 3
`,
		},
		{
			Name:    "matter.linear",
			Headers: []string{"[matter.linear]"},
			Content: `# [matter.linear] - Linear adapter for upstream tickets.
# [matter.linear]
# enabled = false
# team = "MAR"
# ready_state = "Ready"
# in_progress_state = "In Progress"
# done_state = "Done"
# api_key_env = "LINEAR_API_KEY"
`,
		},
	}
}

// DefaultTOML returns the full rendered template: header followed by
// every block joined by a blank line.
func DefaultTOML() string {
	var b strings.Builder
	b.WriteString(Header)
	for _, blk := range Blocks() {
		b.WriteString("\n")
		b.WriteString(blk.Content)
	}
	return b.String()
}

// Options control Run's behavior.
type Options struct {
	// Force rewrites an existing spore.toml with the full template.
	// Ignored when Sections is non-empty.
	Force bool
	// Sections, when non-empty, switches Run into merge mode: only the
	// named blocks are appended (in template order) if their canonical
	// headers are absent. Unknown names are an error.
	Sections []string
}

// Result describes what Run did.
type Result struct {
	Path        string
	Created     bool
	Overwritten bool
	NoOp        bool
	Added       []string
}

// Run is the entry point. With no Sections it creates spore.toml from
// the full template (or no-ops on an existing file unless Force is
// set). With Sections it appends the named blocks to the file
// (creating one if missing), skipping any whose canonical headers are
// already present.
func Run(root string, opts Options) (Result, error) {
	path := filepath.Join(root, "spore.toml")
	res := Result{Path: path}

	existing, exists, err := readIfExists(path)
	if err != nil {
		return res, err
	}

	if len(opts.Sections) == 0 {
		if exists && !opts.Force {
			res.NoOp = true
			return res, nil
		}
		if err := os.WriteFile(path, []byte(DefaultTOML()), 0o644); err != nil {
			return res, err
		}
		if exists {
			res.Overwritten = true
		} else {
			res.Created = true
		}
		return res, nil
	}

	blocks := Blocks()
	byName := map[string]Block{}
	order := []string{}
	for _, b := range blocks {
		byName[b.Name] = b
		order = append(order, b.Name)
	}
	want := map[string]bool{}
	for _, s := range opts.Sections {
		if _, ok := byName[s]; !ok {
			return res, fmt.Errorf("init: unknown section %q", s)
		}
		want[s] = true
	}

	have := presentSections(string(existing))
	out := string(existing)
	if !exists {
		out = Header
	}
	for _, name := range order {
		if !want[name] {
			continue
		}
		blk := byName[name]
		if anyHeaderPresent(have, blk.Headers) {
			continue
		}
		out = appendBlock(out, blk.Content)
		res.Added = append(res.Added, name)
	}

	if !exists && len(res.Added) == 0 {
		res.NoOp = true
		return res, nil
	}
	if exists && len(res.Added) == 0 {
		res.NoOp = true
		return res, nil
	}
	if err := os.WriteFile(path, []byte(out), 0o644); err != nil {
		return res, err
	}
	if !exists {
		res.Created = true
	}
	return res, nil
}

func readIfExists(path string) ([]byte, bool, error) {
	b, err := os.ReadFile(path)
	if err == nil {
		return b, true, nil
	}
	if os.IsNotExist(err) {
		return nil, false, nil
	}
	return nil, false, err
}

// presentSections scans content for active (uncommented) `[section]`
// header lines and returns the set of headers found.
func presentSections(content string) map[string]bool {
	out := map[string]bool{}
	scanner := bufio.NewScanner(strings.NewReader(content))
	for scanner.Scan() {
		line := strings.TrimSpace(stripComment(scanner.Text()))
		if line == "" {
			continue
		}
		if strings.HasPrefix(line, "[") && strings.HasSuffix(line, "]") {
			out[line] = true
		}
	}
	return out
}

func anyHeaderPresent(have map[string]bool, headers []string) bool {
	for _, h := range headers {
		if have[h] {
			return true
		}
	}
	return false
}

func appendBlock(existing, block string) string {
	if existing == "" {
		return block
	}
	if !strings.HasSuffix(existing, "\n") {
		existing += "\n"
	}
	if !strings.HasSuffix(existing, "\n\n") {
		existing += "\n"
	}
	return existing + block
}

// stripComment trims everything after a bare `#`. A `#` inside a
// quoted value is preserved so spore.toml string values that contain
// `#` parse as a single token.
func stripComment(line string) string {
	inQuote := byte(0)
	for i := 0; i < len(line); i++ {
		ch := line[i]
		switch {
		case inQuote != 0:
			if ch == inQuote {
				inQuote = 0
			}
		case ch == '"' || ch == '\'':
			inQuote = ch
		case ch == '#':
			return line[:i]
		}
	}
	return line
}
