name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Check
        run: nix develop --command just check

      - name: Build
        run: nix develop --command just build

      - name: Coverage
        run: nix develop --command just coverage

      - name: Upload coverage
        if: github.event_name != 'pull_request'
        uses: codecov/codecov-action@v5
        with:
          files: ./coverage/coverage.out
          flags: go
          name: spore-go
          fail_ci_if_error: true
          use_oidc: true
